version: 2
project_name: slack-cli

builds:
  - builder: zig
    binary: slack-cli
    targets:
      - aarch64-macos
      - x86_64-linux
      - x86_64-windows
    flags:
      - -Doptimize=ReleaseSafe

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

homebrew_casks:
  - repository:
      owner: ainoya
      name: slack-cli
    directory: Casks
    homepage: "https://github.com/ainoya/slack-cli"
    description: "Slack CLI tool"
