version: 2
project_name: slack-cli

builds:
  - builder: zig
    binary: slack-cli
    targets:
      - aarch64-macos
      - x86_64-linux
      - x86_64-windows
    flags:
      - -Doptimize=ReleaseSafe

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

brews:
  - repository:
      owner: ainoya
      name: slack-cli
    directory: Formula
    homepage: "https://github.com/ainoya/slack-cli"
    description: "Slack CLI tool"
    install: |
      bin.install "slack-cli"
