# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-cli" do
  name "slack-cli"
  desc "Slack CLI tool"
  homepage "https://github.com/ainoya/slack-cli"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-cli"

  on_macos do
    on_arm do
      url "https://github.com/ainoya/slack-cli/releases/download/v#{version}/slack-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "d921d0cabf6220f632ae2ca1726eaa4c95d5b902be61da0028e45d5ae8894f86"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ainoya/slack-cli/releases/download/v#{version}/slack-cli_#{version}_linux_amd64.tar.gz"
      sha256 "cc0848e99513042b54234bd5804a6646779a5494dbc5b88754a3f7c071bbce6e"
    end
  end

  # No zap stanza required
end
