# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackCli < Formula
  desc "Slack CLI tool"
  homepage "https://github.com/ainoya/slack-cli"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ainoya/slack-cli/releases/download/v0.0.5/slack-cli_0.0.5_darwin_arm64.tar.gz"
      sha256 "26db68ef996272ac2d378bf22c5828cedbf68d5df67d483cb9ae7bc7a143d900"

      def install
        bin.install "slack-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ainoya/slack-cli/releases/download/v0.0.5/slack-cli_0.0.5_linux_amd64.tar.gz"
      sha256 "830102b72df59b0f5c5540b78286d92dc210c1fc039bf61b5ab67634a3f73ff1"
      def install
        bin.install "slack-cli"
      end
    end
  end
end
